{
 "title": "Spot Ocean Scaling and Cost Optimization Dashboard",
 "description": "This dashboard provides real-time insights into the scaling, cost, usage, and right-sizing activities managed by Spot Ocean within your Kubernetes cluster. It showcases metrics related to node provisioning, optimization, cost efficiency, and recovery operations. The visualizations help you understand how Spot Ocean dynamically manages Kubernetes cluster resources to ensure optimal performance, cost savings, and high availability. Key actions such as scale-ups, scale-downs, node replacements, and manual interventions are highlighted to give a comprehensive view of your cluster's operational status and health.\r\n\r\nIt includes comprehensive data on compute, storage, and networking expenses, helping you monitor and optimize cloud spending. Visualizations highlight the cost distribution across different resource types and track usage patterns over time. This information empowers customers to make informed decisions about resource allocation, identify cost-saving opportunities, and ensure efficient utilization of cloud infrastructure. Additionally, the dashboard enables the evaluation of Ocean's right-sizing capability, demonstrating how efficient resource adjustments contribute to cost reduction while maintaining optimal cluster performance.",
 "tags": [
  "Spot Ocean",
  "Cluster Cost Optimization",
  "Scaling",
  "Right Sizing"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "ocean_id",
    "label": "Ocean Cluster ID",
    "query": {
     "query": "label_values(ocean_controller_heartbeat_info,ocean_id)"
    }
   },
   {
    "name": "ocean_name",
    "label": "Ocean Cluster Name",
    "query": {
     "query": "label_values(ocean_controller_heartbeat_info{ocean_id=\"$ocean_id\"},ocean_name)"
    }
   },
   { "name": "interval", "label": "Aggregation Interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ocean Controller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ocean_controller_heartbeat_info{ocean_id=\"$ocean_id\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Kubernetes Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(ocean_compute_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Workloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (resource_name) (\n    sum by (resource_name) (ocean_compute_cost{ocean_id=\"$ocean_id\"})\n    or\n    sum by (resource_name) (ocean_storage_cost{ocean_id=\"$ocean_id\"})\n    or\n    sum by (resource_name) (ocean_networking_cost{ocean_id=\"$ocean_id\", resource_type!='Node'})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilization", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 5 } },
  {
   "title": "Nodes Managed by Ocean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potential Monthly Max. Savings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(potential_savings)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ocean_total_pod_vcpu_requests{ocean_id=\"$ocean_id\"}) / sum(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ocean_total_pod_memory_requests{ocean_id=\"$ocean_id\"}) / sum(ocean_allocatable_memory_gibs{ocean_id=\"$ocean_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (ocean_total_pod_gpu_requests) /sum(ocean_allocatable_gpu_units{ocean_id=\"$ocean_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
    { "title": "Allocatable Resources", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 190 } },
    { "title": "Ocean Limit", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 6, "y": 190 } },
    {
     "title": "Ocean Nodes By Spot/OD/SP/RI",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (lifecycle)(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ocean Nodes By AZ",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (az)(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocatable VCPU By Spot/OD/SP/RI",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (lifecycle)(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocatable VCPU by AZ",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (az)(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VCPU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_memory_gibs{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_gpu_units{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VCPU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "ocean_cluster_limits_cpu_vcpu{ocean_id=\"$ocean_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Headroom Resources", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 194 } },
    { "title": "Ocean Limit", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 6, "y": 194 } },
    {
     "title": "VCPU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_headroom_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_headroom_memory_gibs{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ocean_allocatable_headroom_gpu_units{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "ocean_cluster_limits_memory_gib{ocean_id=\"$ocean_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Nodes Managed by Ocean Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
    {
     "title": "Nodes Count Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes Count By Spot/OD/SP/RI Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (lifecycle)(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocatable VCPU By Spot/OD/SP/RI Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 215 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (lifecycle)(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes Count By AZ Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (az)(ocean_managed_nodes{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocatable VCPU By AZ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (az)(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Resources Utilization Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 239 } },
    {
     "title": "CPU Utilization Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_total_pod_vcpu_requests{ocean_id=\"$ocean_id\"}) / sum(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_total_pod_memory_requests{ocean_id=\"$ocean_id\"}) / sum(ocean_allocatable_memory_gibs{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Utilization Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (ocean_total_pod_gpu_requests) /sum(ocean_allocatable_gpu_units{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Pods Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 264 } },
    {
     "title": "Average Time to Get to Ready State Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(\n  kube_pod_status_container_ready_time \n  - \n  kube_pod_start_time\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Pods Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Scaling Activity Overview", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 281 } },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 282 },
     "options": {
      "content": "<ul>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">Scale Up</span> - Node provisioned to satisfy pending pods/headroom requests.</li>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">Scale Down</span> - Node terminated to optimize resource utilization.</li>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">On Demand to Spot Replacement</span> - Spot node created instead of On Demand Node.</li>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">Lower Cost Replacement</span> - Node replaced with a cheaper Node.</li>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">Shutdown Hours</span> - Node stopped during scheduled hours.</li>\n  <li><span style=\"color:rgb(115, 191, 105); font-weight:bold;\">Reserved Capacity Utilization</span> - Node replaced with a Node from Reserved Instances or Saving Plans pools.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Recovery</span> - Node provisioned to replace a Spot Node reclaimed by Cloud Provider.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Auto Healing</span> - Node provisioned instead of an unhealthy Node.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Failed To Register</span> - Node failed to register to cluster.</li>\n  <li><span style=\"color:rgb(87, 148, 242); font-weight:bold;\">Workload Migration</span> - Node provisioned due to a workload migration process.</li>\n  <li><span style=\"color:rgb(87, 148, 242); font-weight:bold;\">Cluster Roll</span> - Node upgrade initiated by Administrator.</li>\n  <li><span style=\"color:rgb(87, 148, 242); font-weight:bold;\">Manual Scaling</span> - Node launched or terminated manually by Administrator.</li>\n</ul>"
     }
    },
    {
     "title": "Scale Up Actions Summary",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 6, "y": 282 },
     "targets": [
      {
       "expr": "sum by (reason, az, vm_type) (ocean_nodes_added_total{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scale Down Actions Summary",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 282 },
     "targets": [
      {
       "expr": "sum by (reason, az, vm_type) (ocean_nodes_removed_total{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes Added Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_current_nodes_added{ocean_id=\"$ocean_id\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes Removed Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_current_nodes_removed{ocean_id=\"$ocean_id\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Scaling Activity Overview",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 312 }
    },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 313 },
     "options": {
      "content": "<ul>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Launch error</span> - Failed to scale up. Technical failure to launch required instances.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Cluster max instance count reached</span> - Failed to scale up. Clusters reached maximum instance count running</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">VNG max instance count reached</span> - Failed to scale up. Virtual Node Group reached the maximum instance count running.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">VNG can't meet constraints</span> - Failed to scale up. Virtual Node Group's onfiguration could not satisfy the Pod's constraints.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Topology constraints not met</span> - Failed to scale up. Pod topology spread constraints could not be satisfied by the current group configuration.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Affinity rules not met</span> - Failed to scale up. Pod's affinity/ anti-affinity could not be satisfied by the Virtual Node Group's configuration</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">No matching instances found</span> - Failed to scale up. No instances matched all the pods' requested resources.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">PVC issue</span> - Failed to scale up. PVC requiements can't be handled.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">VNG min instance count reached</span> - Failed to scale down. Virtual Node Group has reached the minimum capacity of running instances.</li>\n  <li><span style=\"color:rgb(242, 73, 92); font-weight:bold;\">Cluster min instance count reached</span> - Failed to scale down. Cluster have reached the minimum capacity of running instances.</li>\n</ul>"
     }
    },
    {
     "title": "Failed Scale Up Actions Summary",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 6, "y": 313 },
     "targets": [
      {
       "expr": "sum by (reason, vng_id, vng_name) (ocean_failed_scale_ups_total{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Scale Down Actions Summary",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 313 },
     "targets": [
      {
       "expr": "sum by (reason, vng_id, vng_name) (ocean_failed_scale_downs_total{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Scales Up Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 327 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ocean_current_failed_scale_ups{ocean_id=\"$ocean_id\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Ocean Controllers Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 335 } },
    {
     "title": "Ocean Kubernetes Controller Status Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 336 },
     "targets": [
      {
       "expr": "ocean_controller_heartbeat_info{ocean_id=\"$ocean_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ocean Kubernetes Controllers Pods Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 344 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{pod=~\"ocean-controller-ocean-kubernetes-controller-.*\", phase=\"Running\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ocean Kubernetes Controllers Memory Consumption Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod_base) (\n  label_replace(container_memory_usage_bytes{pod=~\"ocean-controller-ocean-kubernetes-controller-.*\", container!=\"POD\", container!=\"\"}, \"pod_base\", \"ocean-kubernetes-controller-v2\", \"pod\", \"ocean-controller-ocean-kubernetes-controller-.*\") or\n  label_replace(container_memory_usage_bytes{pod=~\"spotinst-kubernetes-cluster-controller-.*\", container!=\"POD\", container!=\"\"}, \"pod_base\", \"ocean-kubernetes-controller-v1\", \"pod\", \"spotinst-kubernetes-cluster-controller-.*\")\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ocean Metrics Controllers Memory Consumption Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod_base) (\n  label_replace(container_memory_usage_bytes{pod=~\"ocean-controller-metrics-server-.*\", container!=\"POD\", container!=\"\"}, \"pod_base\", \"ocean-metrics-server\", \"pod\", \"ocean-controller-metrics-server-.*\") or\n  label_replace(container_memory_usage_bytes{pod=~\"spot-ocean-metric-exporter-.*\", container!=\"POD\", container!=\"\"}, \"pod_base\", \"ocean-metric-exporter\", \"pod\", \"spot-ocean-metric-exporter-.*\")\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost and Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 532 } },
    {
     "title": "MTD Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 533 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "((sum(ocean_compute_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Cost Breakdown",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 533 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(sum(ocean_compute_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
       "legendFormat": "Compute"
      },
      {
       "expr": "(sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
       "legendFormat": "Storage"
      },
      {
       "expr": "(sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
       "legendFormat": "Network"
      }
     ]
    },
    {
     "title": "Cluster Cost Overtime  vs Previous Period",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 533 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(sum(ocean_compute_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) +(sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))+(sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(ocean_compute_cost{ocean_id=\"$ocean_id\"} offset $interval) or on() vector(0)) +(sum(ocean_storage_cost{ocean_id=\"$ocean_id\"} offset $interval) or on() vector(0))+(sum(ocean_networking_cost{ocean_id=\"$ocean_id\"} offset $interval) or on() vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Daily Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 537 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "((sum(ocean_compute_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)) + (sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)))/7",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Compute and Storage Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 541 } },
    {
     "title": "Average Cost per CPU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 542 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(ocean_compute_cost{ocean_id=\"$ocean_id\"})) / (sum(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU by Instance Lifecycle Breakdown",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 542 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (lifecycle)(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Storage Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 542 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(sum(ocean_storage_cost{ocean_id=\"$ocean_id\"}) or on() vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Cost Breakdown",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 542 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (storage_type)(ocean_storage_cost{ocean_id=\"$ocean_id\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 546 } },
    { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 12, "y": 546 } },
    {
     "title": "Compute Cost Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 550 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (resource) (\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"ds\"}, \"resource\", \"DaemonSet\", \"resource_type\", \"ds\") or \nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"d\"}, \"resource\", \"Deployment\", \"resource_type\", \"d\") or\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"headroom\"}, \"resource\", \"Headroom\", \"resource_type\", \"headroom\") or\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"j\"}, \"resource\", \"Job\", \"resource_type\", \"j\") or\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"rs\"}, \"resource\", \"ReplicaSet\", \"resource_type\", \"rs\") or\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type=\"ss\"}, \"resource\", \"StatefulSet\", \"resource_type\", \"ss\") or\nlabel_replace(ocean_compute_cost{ocean_id=\"$ocean_id\", resource_type!~\"d|ds|headroom|j|rs|ss\"}, \"resource\", \"Other\", \"resource_type\", \".*\")\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Cost Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 550 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (resource_type) (ocean_storage_cost{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (resource) (\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"ds\"}, \"resource\", \"DaemonSet\", \"resource_type\", \"ds\") or \nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"d\"}, \"resource\", \"Deployment\", \"resource_type\", \"d\") or\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"headroom\"}, \"resource\", \"Headroom\", \"resource_type\", \"headroom\") or\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"j\"}, \"resource\", \"Job\", \"resource_type\", \"j\") or\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"rs\"}, \"resource\", \"ReplicaSet\", \"resource_type\", \"rs\") or\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type=\"ss\"}, \"resource\", \"StatefulSet\", \"resource_type\", \"ss\") or\nlabel_replace(ocean_cpu_usage{ocean_id=\"$ocean_id\", resource_type!~\"d|ds|headroom|j|rs|ss\"}, \"resource\", \"Other\", \"resource_type\", \".*\")\n) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "sum by (resource) (\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"ds\"}, \"resource\", \"DaemonSet\", \"resource_type\", \"ds\") or \nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"d\"}, \"resource\", \"Deployment\", \"resource_type\", \"d\") or\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"headroom\"}, \"resource\", \"Headroom\", \"resource_type\", \"headroom\") or\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"j\"}, \"resource\", \"Job\", \"resource_type\", \"j\") or\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"rs\"}, \"resource\", \"ReplicaSet\", \"resource_type\", \"rs\") or\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type=\"ss\"}, \"resource\", \"StatefulSet\", \"resource_type\", \"ss\") or\nlabel_replace(ocean_memory_usage{ocean_id=\"$ocean_id\", resource_type!~\"d|ds|headroom|j|rs|ss\"}, \"resource\", \"Other\", \"resource_type\", \".*\")\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Network Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 566 } },
    {
     "title": "Total Network Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 567 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(ocean_networking_cost{ocean_id=\"$ocean_id\"}) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Cost By Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 567 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (traffic_type) (ocean_networking_cost)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Intra AZ Network Usage Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 567 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_usage{ocean_id=\"$ocean_id\", traffic_type=\"intraAZ\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Network Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 571 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(ocean_networking_usage{ocean_id=\"$ocean_id\"}) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter AZ Network Cost Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 575 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_cost{ocean_id=\"$ocean_id\", traffic_type=\"interAZ\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter AZ Network Usage Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 575 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_usage{ocean_id=\"$ocean_id\", traffic_type=\"interAZ\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internet Network Cost Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 583 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_cost{ocean_id=\"$ocean_id\", traffic_type=\"internet\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internet Network Usage Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 583 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_usage{ocean_id=\"$ocean_id\", traffic_type=\"internet\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter Region Network Cost Overtime",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 591 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_cost{ocean_id=\"$ocean_id\", traffic_type=\"interRegion\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inter Region Network Usage Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 591 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum (ocean_networking_usage{ocean_id=\"$ocean_id\", traffic_type=\"interRegion\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Right Sizing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "VCPU Suggestions Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 755 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cpu_recommendations{ocean_id=\"$ocean_id\"})/1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ocean_cpu_usage{ocean_id=\"$ocean_id\"})/1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(ocean_allocatable_cpu_vcpus{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Suggestions Overtime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 755 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "sum(memory_recommendations{ocean_id=\"$ocean_id\"})/1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(ocean_memory_usage{ocean_id=\"$ocean_id\"})/1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(ocean_allocatable_memory_gibs{ocean_id=\"$ocean_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Workloads with Potential Monthly Max. Savings",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 763 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(5,\n    sum by (resource_name) (potential_savings))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}